services: 
    katsudoc-frontend:
        container_name: katsudoc-frontend
        build:
            context: . #if your Dockerfile is not at the same level change the path here (./frontend)
            target: development
        restart: always
        command: npm run dev
        environment:
            - NODE_ENV=development 
            #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
            #- WATCHPACK_POLLING=true
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        ports:
            - 3000:3000